# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-03 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['title'], 'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=10, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='sizecount',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='sizecount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_count', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='sizecount',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_count', to='product.Size'),
        ),
    ]
