# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-07 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default='', max_length=5000, verbose_name='Деталі товару'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_large',
            field=models.ImageField(blank=True, height_field='height_field', help_text='Зображення товару для детального перегляду', null=True, upload_to=product.models.upload_location2, verbose_name='Велика картинка', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', help_text='Зображення товару', null=True, upload_to=product.models.upload_location, verbose_name='Картинка', width_field='width_field'),
        ),
    ]
