# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-11 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170507_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=10, unique=True, verbose_name='Размер'),
        ),
    ]
