# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-23 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20170423_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
