# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-04 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['object_id', 'id'], 'verbose_name': 'Пункти категорії', 'verbose_name_plural': 'Пункти категорій'},
        ),
    ]
